### ISSUE TITLE
i read your paper, you said the params of kiunet is much small than unet cause you only have 32,64,128 conv. but the kiunet in model.py seems not like that,why?

### ISSUE THREAD

**Issue by jiangjiaxi20** [jeya-maria-jose/KiU-Net-pytorch#11]

**Comment by jeya-maria-jose** [comment]
The kiunet 2D that we use for image segmentation experiments does have 32,64,128 conv. For LITS dataset, in model.py we in fact have 16,32,64 number of filters which are less because the input was larger in size compared to 2D experiments and we wanted to release a code that was able to fit in a 12 GB GPU. Please feel free to increase the number of filters if memory is not an issue.
