### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by mamba10-lab** [jeya-maria-jose/KiU-Net-pytorch#22]
Hi, thanks for the great work you've done. I am trying to use either kiunet or reskiunet models with images of size 512*512, but it doesn't work with such size on VRAM=40gb with batch size =1. It works on smaller images (256*256, batchsize = 3). It also takes too long to train it... I find it a little bit weird because the model doesn't have too mane parameters (only 300k), I trained much larger models faster (e.g. 3*10^6 parameters), so I am wondering if it is the expected behavior or maybe on new pytorch(i am using 1.7) it isn't efficient? Maybe you know some ways how I can improve the memory consumption and speed?

**Comment by jeya-maria-jose** [comment]
Hi, 

Yeah. It does take a long time and memory to train for images for higher resolution. This happens as the feature map size in the bottle neck of Kite-Net branch is of high resolution and takes more compute power even though the number of parameters is less. Easy get-around to this problem is to use patch-wise training or remove some layers in the kite-net branch.

Any other fixes to this issue is welcome !

**Comment by mamba10-lab** [comment]
I will try that, thank you for the reply
