### ISSUE TITLE
for the LiTS dataset, why you # the kiunet model in net/models.py

### ISSUE THREAD

**Issue by jiangjiaxi96** [jeya-maria-jose/KiU-Net-pytorch#5]

**Comment by jeya-maria-jose** [comment]
The commented model is just an extended model with more layers of the kiunet model found in net/models.py. Feel free to use that if the number of parameters is not a constraint for your experiments.

**Comment by jiangjiaxi20** [comment]
thank you so much! In the LiTS file.  i read your paper, the # kiunet seems to be the structure you mentioned in your paper, the un-#-kiunet seems do not fit your structure in your paper at all. And in the line 656 net=segnet(training=True), should i change this to net=kiunet(training=true) in order to use the kiunet?

**Comment by jeya-maria-jose** [comment]
Hi, Yes, loading the # kiunet model requires more memory and takes more time to train, so un-#-kiunet is a simpler version of it which gives comparable performance. To get exact results as of paper, please use # kiunet model. Yes, change line 656 to specify the model.

**Comment by jiangjiaxi96** [comment]
Thank you so much for your help!!! but I trained the model, and run the val.py. the pred.nii did not show the tumor parts. I only see the Liver contour in the segmentation results.

**Comment by jeya-maria-jose** [comment]
Yes, it will not. We train the network only to detect liver in this work. We do not consider the second class (tumor).

**Comment by jiangjiaxi96** [comment]
What is your best dice and jacquard score in the LiTS dataset by using the minuet
